---
language: python
dist: bionic
services: docker
python:
  # - "3.5"
  # - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - ROLE_NAME: "bootstrap"
    - NAMESPACE: "tehtbl"
  matrix:
    - IMAGE="debian" TAG="stable"
    - IMAGE="debian" TAG="testing"
    - IMAGE="debian" TAG="unstable"
    - IMAGE="ubuntu" TAG="xenial"
    - IMAGE="ubuntu" TAG="bionic"
    - IMAGE="ubuntu" TAG="devel"

matrix:
  allow_failures:
    - env: IMAGE="debian" TAG="unstable"
    - env: IMAGE="ubuntu" TAG="devel"

install:
  - pip install --upgrade pip
  - pip install tox

script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-${ROLE_NAME} ${ROLE_NAME}
  - cd ${ROLE_NAME}

  # get current Python version for Tox testing
  - export PY_VERSION="py${TRAVIS_PYTHON_VERSION//.}"
  - echo "${PY_VERSION}"

  # Run Molcule tests with help of Tox
  # - tox -e "${PY_VERSION}-ansible-{previous,current,next}" --parallel all
  # - tox -e "${PY_VERSION}-ansible-{previous,current,next}"
  - tox -e "${PY_VERSION}-ansible-{current}"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: true
