---
language: python
services: docker

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  global:
    - role_name: bootstrap
    - namespace: "tehtbl"
  matrix:
    # - image="alpine" tag="3.9"
    # # - image="alpine" tag="latest"
    # # - image="alpine" tag="edge"
    # # - image="debian" tag="stable"
    # - image="debian" tag="testing"
    # - image="debian" tag="unstable"
    # # - image="ubuntu" tag="xenial"
    # - image="ubuntu" tag="bionic"
    # # - image="ubuntu" tag="devel"
    - image="ubuntu" tag="bionic"

# matrix:
#   allow_failures:
#     - env: image="alpine" tag="edge"
#     - env: image="debian" tag="unstable"
#     - env: image="ubuntu" tag="devel"
#
# cache:
#   - pip
#
# install:
#   - pip install --upgrade pip
#   - pip install tox
#   - pip install molecule docker
#
# script:
#   - tox --parallel all

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-${role_name} ${namespace}.${role_name}
  - cd ${namespace}.${role_name}

script:
  # Run tests.
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
#   email: true
