---
- name: install using registered package manager
  remote_user: "{{ bootstrap_remote_user | default(omit) }}"
  block:
    - name: install software for Debian
      raw: "LANG=C apt-get update && apt-get install -y {{ bootstrap_packages }}"
      when:
        - debian.rc == 0
        - bootstrap_packages is defined
      register: debianresult
      changed_when:
        - "' 0 newly installed' not in debianresult.stdout"
      until: debianresult is succeeded
      retries: "{{ bootstrap_retries }}"

    - name: install software for Ubuntu
      raw: "LANG=C apt-get update && apt-get install -y {{ bootstrap_packages }}"
      when:
        - ubuntu.rc == 0
        - bootstrap_packages is defined
      register: ubunturesult
      changed_when:
        - "' 0 newly installed' not in ubunturesult.stdout"
      until: ubunturesult is succeeded
      retries: "{{ bootstrap_retries }}"
